apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-user-deployment
  namespace: k8s-course
  labels:
    app: pg-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-user
  template:
    metadata:
      labels:
        app: pg-user
    spec:
      containers:
        - name: postgres-user
          image: postgres:15.2-alpine
          ports:
            - containerPort: 5432
          env:
            - name: PGPORT
              value: "5432"
            - name: POSTGRES_DB
              value: user-service
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: pass

---

apiVersion: v1
kind: Service
metadata:
  name: pg-user-service
  namespace: k8s-course
spec:
  selector:
    app: pg-user
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432