server:
  port: 8081

user:
  service:
    base:
      path: ${user_service_base_path}

spring:
  application:
    name: post-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  sql:
    init:
      mode: always

management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info


info:
  application:
    version: 1.0.9