apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-user-statefulset
  namespace: {{ .Values.namespace }}
  labels:
    app: pg-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-user
  template:
    metadata:
      labels:
        app: pg-user
    spec:
      containers:
        - name: postgres-user
          image: postgres:15.2-alpine
          ports:
            - containerPort: 5432
          env:
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: user_pgport
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: user_postgres_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: user_datasource_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: user_datasource_password
          volumeMounts:
            - name: pg-user-db
              mountPath: /var/lib/postgresql/data
              subPath: userdata
            - name: pg-schema-script
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -d pg-user
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -d pg-user
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -d pg-user
            periodSeconds: 10
      volumes:
        - name: pg-schema-script
          configMap:
            name: app-configmap
            items:
              - key: "user_schema.sql"
                path: "schema.sql"
  volumeClaimTemplates:
    - metadata:
        name: pg-user-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "hostpath"
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: pg-user-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: pg-user
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432