apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: post
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: epamgrzegorzchabiera/post-service:1.0.9
          ports:
            - containerPort: 8081
          env:
            - name: user_service_base_path
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: user_service_base_path
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: post_datasource_url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: post_datasource_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: post_datasource_password
          startupProbe:
            httpGet:
              path: /posts/1
              port: 8081
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: post
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
