server:
  port: 8080

spring:
  application:
    name: user-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  sql:
    init:
      mode: always