apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: k8s-course
data:
  user_datasource_url: jdbc:postgresql://${PG_USER_SERVICE_SERVICE_HOST}:5432/user-service
  post_datasource_url: jdbc:postgresql://${PG_POST_SERVICE_SERVICE_HOST}:5431/post-service
  user_service_base_path: http://${USER_SERVICE_SERVICE_HOST}:8080
  user_pgport: "5432"
  user_postgres_db: user-service
  app-configmap: "5431"
  post_postgres_db: post-service