apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: k8s-course
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: epamgrzegorzchabiera/user-service:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: user_datasource_url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: user_datasource_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: user_datasource_password

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: k8s-course
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
