apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  namespace: k8s-course
  labels:
    app: post
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: epamgrzegorzchabiera/post-service:1.0.1
          ports:
            - containerPort: 8081
          env:
            - name: user_service_base_path
              value: http://${USER_SERVICE_SERVICE_HOST}:8080
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://${PG_POST_SERVICE_SERVICE_HOST}:5431/post-service
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: pass

---

apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: k8s-course
spec:
  type: NodePort
  selector:
    app: post
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
